/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdriver;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class MainForm extends javax.swing.JFrame {

    BufferedImage img;
    BufferedImage img1;
    String imgFile1 = "D:\\Java\\javaprojects\\BDriver\\examples\\auc1.jpg";
    String imgFile2 = "D:\\Java\\javaprojects\\BDriver\\examples\\auc2.jpg";
    String imgFile3 = "D:\\Java\\javaprojects\\BDriver\\examples\\auc3.jpg";
    int level = 0;
    private ServerSocket serverSocket;
    private Socket cs;
    InputStream in;
    OutputStream out;
    int length = 0;
    byte[] incoming;

    private boolean status = true;  // статус соединения\открытого ClientSocker
    private long time1;
    private long time2;
    private int timeLimit = 10000;
    boolean switcher = true;

    private void makeConnection() {

        try {
            serverSocket = new ServerSocket(5656);
            System.out.println("Client starting, waiting accept");

            Socket clientSocket = new Socket();
            clientSocket = serverSocket.accept();
            System.out.println("Client started");
            while (true) {
                if (!clientSocket.isClosed()) { // подлежит доработке для адекватной отработки кода

                    in = clientSocket.getInputStream();
                    out = clientSocket.getOutputStream();
                    incoming = new byte[256];

                    System.out.println("Client query(" + length + " bytes):" + new String(incoming).trim());

//                    String reply = makeAnswer(incoming); // выполняется метод, который возвращает устройству требуемый ответ в зависимости от пришедшего пакета
//
//                    if (reply.equals("empty")) { //если вернулось empty - устройство разорвало соединение со своей стороны.
//                        in.close();
//                        out.close();
//                        //cs.close();
//                        serverSocket.close();
//                        Start.mf.setWatcherStatus(device, false); // соединение разорвано и требуется запустить новый поток с новым Listener для этого порта и устройства
//                        Start.mf.deviceConnection(device.getId(), false);
//                        Start.mf.deviceStatus(device.getId(), false);
//                    } else {
//
//                        out.write(reply.getBytes());}
                    System.out.println("DeviceListener: getPacket executed");

                }
            }
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        fullfilldata();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        panelImage = new javax.swing.JLabel();
        labMin = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        panelImageMin = new javax.swing.JLabel();
        TFmin = new javax.swing.JTextField();
        labMax = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        panelImageMax = new javax.swing.JLabel();
        TFmax = new javax.swing.JTextField();
        labPrice1 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        panelPrice1 = new javax.swing.JLabel();
        TFprice1 = new javax.swing.JTextField();
        labPrice2 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        panelPrice2 = new javax.swing.JLabel();
        TFprice2 = new javax.swing.JTextField();
        labQ1 = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        panelQ1 = new javax.swing.JLabel();
        TFq1 = new javax.swing.JTextField();
        labQ2 = new javax.swing.JLabel();
        panel7 = new javax.swing.JPanel();
        panelQ2 = new javax.swing.JLabel();
        TFq2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Нарезать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 90, 90, 23);

        jButton2.setText("Определить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 90, 100, 23);

        panel1.setBackground(new java.awt.Color(153, 255, 153));
        panel1.setPreferredSize(new java.awt.Dimension(460, 50));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(panel1);
        panel1.setBounds(40, 30, 460, 50);

        labMin.setText("Min");
        getContentPane().add(labMin);
        labMin.setBounds(50, 130, 100, 14);

        panel2.setBackground(new java.awt.Color(153, 255, 153));
        panel2.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageMin, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageMin, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        getContentPane().add(panel2);
        panel2.setBounds(50, 150, 100, 20);

        TFmin.setText("jTextField1");
        getContentPane().add(TFmin);
        TFmin.setBounds(170, 150, 59, 20);

        labMax.setText("Max");
        getContentPane().add(labMax);
        labMax.setBounds(280, 130, 100, 14);

        panel3.setBackground(new java.awt.Color(153, 255, 153));
        panel3.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageMax, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageMax, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        getContentPane().add(panel3);
        panel3.setBounds(280, 150, 100, 20);

        TFmax.setText("jTextField1");
        getContentPane().add(TFmax);
        TFmax.setBounds(400, 150, 59, 20);

        labPrice1.setText("Цена1");
        getContentPane().add(labPrice1);
        labPrice1.setBounds(50, 240, 100, 14);

        panel4.setBackground(new java.awt.Color(153, 255, 153));
        panel4.setPreferredSize(new java.awt.Dimension(80, 17));

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
        );

        getContentPane().add(panel4);
        panel4.setBounds(50, 260, 80, 17);

        TFprice1.setText("jTextField2");
        getContentPane().add(TFprice1);
        TFprice1.setBounds(150, 260, 59, 20);
        TFprice1.getAccessibleContext().setAccessibleDescription("");

        labPrice2.setText("jLabel2");
        getContentPane().add(labPrice2);
        labPrice2.setBounds(280, 240, 100, 14);

        panel5.setBackground(new java.awt.Color(153, 255, 153));
        panel5.setPreferredSize(new java.awt.Dimension(80, 17));

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
        );

        getContentPane().add(panel5);
        panel5.setBounds(280, 260, 80, 17);

        TFprice2.setText("jTextField2");
        getContentPane().add(TFprice2);
        TFprice2.setBounds(400, 260, 59, 20);
        TFprice2.getAccessibleContext().setAccessibleDescription("");

        labQ1.setText("Всего продано");
        getContentPane().add(labQ1);
        labQ1.setBounds(50, 290, 100, 14);

        panel6.setBackground(new java.awt.Color(153, 255, 153));
        panel6.setPreferredSize(new java.awt.Dimension(80, 17));

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQ1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQ1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
        );

        getContentPane().add(panel6);
        panel6.setBounds(50, 310, 80, 17);

        TFq1.setText("jTextField2");
        getContentPane().add(TFq1);
        TFq1.setBounds(150, 310, 59, 20);
        TFq1.getAccessibleContext().setAccessibleDescription("");

        labQ2.setText("Сейчас на рынке");
        getContentPane().add(labQ2);
        labQ2.setBounds(280, 290, 100, 14);

        panel7.setBackground(new java.awt.Color(153, 255, 153));
        panel7.setPreferredSize(new java.awt.Dimension(80, 17));

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQ2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQ2, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
        );

        getContentPane().add(panel7);
        panel7.setBounds(280, 310, 80, 17);

        TFq2.setText("jTextField2");
        getContentPane().add(TFq2);
        TFq2.setBounds(400, 310, 59, 20);
        TFq2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        panelImageMin.setIcon(new ImageIcon(img.getSubimage(880, 390, 100, 20)));

        panelImageMax.setIcon(new ImageIcon(img.getSubimage(1010, 390, 100, 20)));

        panelPrice1.setIcon(new ImageIcon(img.getSubimage(1165, 370, 80, 17)));

        panelPrice2.setIcon(new ImageIcon(img.getSubimage(1170, 392, 80, 17)));

        panelQ1.setIcon(new ImageIcon(img.getSubimage(1275, 370, 80, 17)));

        panelQ2.setIcon(new ImageIcon(img.getSubimage(1280, 392, 80, 17)));
        makeConnection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        MedianFilter mfilter = new MedianFilter(3);
        mfilter.filter(img.getSubimage(1010, 390, 100, 20), img);
        //panelImageMax.setIcon(new ImageIcon(img));

        int a;
        BufferedImage image = img.getSubimage(1010, 390, 100, 20);
//        level++;
//       
//        for (int j = 0; j < image.getHeight(); j++) {
//            for (int i = 0; i < image.getWidth(); i++) {
//                a = image.getRGB(i, j);
//                //System.out.println("a="+a);
//                int sr = (Pixel.getRed(a) + Pixel.getGreen(a) + Pixel.getBlue(a)) / 3;
//                image.setRGB(i, j, (sr < level ? Color.BLACK.getRGB() : Color.WHITE.getRGB()));
//            }
//        }
//        System.err.println("level="+level);
        ColorCannyEdgeDetector edgedImage = new ColorCannyEdgeDetector(image);

        //edgedImage.findEdges();
        panelImageMax.setIcon(new ImageIcon(edgedImage.findEdges()));
        EncogRecognitor er = new EncogRecognitor();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void fullfilldata() {
        ImageIcon icon;
        try {

            img = ImageIO.read(new File(imgFile1));
            img1 = ImageIO.read(new File(imgFile1));
            icon = new ImageIcon(img.getSubimage(900, 360, 460, 50));
            panelImage.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Mono(BufferedImage image, int level) {

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFmax;
    private javax.swing.JTextField TFmin;
    private javax.swing.JTextField TFprice1;
    private javax.swing.JTextField TFprice2;
    private javax.swing.JTextField TFq1;
    private javax.swing.JTextField TFq2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labMax;
    private javax.swing.JLabel labMin;
    private javax.swing.JLabel labPrice1;
    private javax.swing.JLabel labPrice2;
    private javax.swing.JLabel labQ1;
    private javax.swing.JLabel labQ2;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JLabel panelImage;
    private javax.swing.JLabel panelImageMax;
    private javax.swing.JLabel panelImageMin;
    private javax.swing.JLabel panelPrice1;
    private javax.swing.JLabel panelPrice2;
    private javax.swing.JLabel panelQ1;
    private javax.swing.JLabel panelQ2;
    // End of variables declaration//GEN-END:variables
}
